server:
  port: 8084
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dan-Elioth/2023distribuidas
          search-paths: config-data
          username: Dan
          password: 123456789
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t
